project_id = "ymnnvlhzdftchppusxkx"

[functions.store-document]
verify_jwt = true

[functions.data-insights-ai]
verify_jwt = true

[functions.news-snippets-ai]
verify_jwt = true

[functions.openai-contextual-news]
verify_jwt = true

[functions.document-analysis]
verify_jwt = true

[functions.ask-waypoint-chat]
verify_jwt = true