// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://ymnnvlhzdftchppusxkx.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Inltbm52bGh6ZGZ0Y2hwcHVzeGt4Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDkyMDcxODUsImV4cCI6MjA2NDc4MzE4NX0.137OyD0AxoVu38ww6x-RecjupfqbflEXFYFL-OtYjvM";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);